version: '3'

services:
  db:
    image:  postgres:10
    networks:
      - db_network
    volumes:
      - dev_postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.envs/.dev/.postgres
  web:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: bash -c "python manage.py makemigrations core  && python manage.py makemigrations codes && python manage.py makemigrations codes && python manage.py makemigrations disabled && python manage.py makemigrations ubication && python manage.py makemigrations items && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./qr:/qr
    depends_on:
      - db
    networks:
      - db_network
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres

networks:
  db_network:
    driver: bridge

volumes:
  dev_postgres_volume:
