version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./qr:/qr
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations core  && python manage.py makemigrations codes && python manage.py makemigrations codes && python manage.py makemigrations disabled && python manage.py makemigrations ubication && python manage.py makemigrations items && python manage.py migrate && gunicorn qr.wsgi -b 0.0.0.0:80"
    volumes:
      - ./qr:/qr
    depends_on:
      - db
    expose:
      - "80"
